(define (problem Problema4)
    (:domain Ejercicio4)
    (:objects
        bruja1 - bruja
        bikini1 - bikini
        zapatilla1 - zapatilla
        player1 - agente
        oscar1 - oscar
        manzana1 - manzana
        princesa1 - princesa
        z4 z5 z3 z1 z7 z6 z2 - zona
    )
    (:init
        (conectado z1 z3 sur)
        (conectado z3 z1 norte)
        (conectado z3 z6 sur)
        (conectado z6 z3 norte)
        (conectado z2 z3 este)
        (conectado z3 z2 oeste)
        (conectado z3 z4 este)
        (conectado z4 z3 oeste)
        (conectado z5 z6 este)
        (conectado z6 z5 oeste)
        (conectado z6 z7 este)
        (conectado z7 z6 oeste)
        (es piedra z7)
        (es piedra z2)
        (es piedra z4)
        (es piedra z6)
        (es bosque z5)
        (es bosque z1)
        (es arena z3)
        (orientado player1 norte)
        (manovacia player1)
        (mochilavacia player1)
        (en bruja1 z1)
        (en bikini1 z3)
        (en zapatilla1 z6)
        (en player1 z2)
        (en oscar1 z5)
        (en manzana1 z5)
        (en princesa1 z7)
        (esbikini bikini1)
        (eszapatilla zapatilla1)
        (= (coste z3 z1) 10)
        (= (coste z1 z3) 10)
        (= (coste z6 z3) 5)
        (= (coste z3 z6) 5)
        (= (coste z3 z2) 10)
        (= (coste z2 z3) 10)
        (= (coste z4 z3) 5)
        (= (coste z3 z4) 5)
        (= (coste z6 z5) 10)
        (= (coste z5 z6) 10)
        (= (coste z7 z6) 5)
        (= (coste z6 z7) 5)
        (= (costeTotal) 0)
        (= (puntosTotales) 0)
        (= (puntos oscar1 bruja1) 4)
        (= (puntos manzana1 bruja1) 10)
        (= (puntos oscar1 princesa1) 5)
        (= (puntos manzana1 princesa1) 1)
    )
    (:goal (AND
          (tieneobjeto  bruja1)
          (tieneobjeto  princesa1)
          (< (costeTotal) 200)
          (>= (puntosTotales) 10)
          )
    )
)
